### ISSUE TITLE
Screenshots in README

### ISSUE THREAD

**Issue by Immortalin** [Sk1erLLC/Elementa#13]
Add screenshots to README and documentation.

**Comment by FalseHonesty** [comment]
Hi, yes I do absolutely plan to do a complete documentation overhaul soon, but I’m waiting until version 2.0.0 is almost feature complete. Also for reference, it would be helpful if you were to not just leave your issue body as the default issue text, thanks :)

**Comment by FalseHonesty** [comment]
Also, to clarify, https://github.com/Sk1erLLC/Elementa/blob/master/docs/components.md has a ton of screenshots, and has been updated in commit ab2f58100931e5965ce3d7911712b3745f5f8c10 to reflect all of the changes in Elementa, as well as all of the new components, so this is a good first step :)

**Comment by FalseHonesty** [comment]
I have also now added documentation for the 1.7.1 to 2.0.0 changes in this commit: https://github.com/Sk1erLLC/Elementa/commit/8f9ac4ed8f813aa1fd5e815dbe295b58d1895392. This also brings a screenshot of all the components directly in the README :)
