### ISSUE TITLE
Enforce a time limit when processing RenderOperations in Window

### ISSUE THREAD

**Issue by mattco98** [Sk1erLLC/Elementa#15]
A single Window should not spend more than, say, 5ms in a single draw call when processing RenderOperations.

**Comment by Sk1er** [comment]
Should be developer configurable as variable per instance of Window

**Comment by FalseHonesty** [comment]
> Should be developer configurable as variable per instance of Window

I disagree, render operations happen globally and aren't tied to an instance of Window. Also, some render operations are enqueued by Elementa internally, so it wouldn't make sense for developer configurations to affect this. I think a sensible default like 5ms is pretty reasonable, considering there are 16.67 millis allowed per frame for a 60fps target.
