### ISSUE TITLE
README.md install instructions do not seem to be up to date and a little bit vague

### ISSUE THREAD

**Issue by tasgon** [Sk1erLLC/Elementa#28]
This project tells people to install the latest snapshot versions by adding `implementation "club.sk1er:Elementa:129-$mcVersion-SNAPSHOT"` in their dependencies section. However, Vigilance specifies "gg.essential:Elementa:339-$mcVersion-SNAPSHOT" instead. 

Also, `$mcVersion` does not seem to be a well explained variable. Generally, variables like that are expected to be replaced version numbers such as "1.16.5". But, looking through the repository's maven-metadata.xml, it seems that the format is different, e.g. $mcVersion = 11602 is used for all 1.16 versions.

**Comment by Sychic** [comment]
Fixed in dc0ccaf
