### ISSUE TITLE
Stenciling performance

### ISSUE THREAD

**Issue by asbyth** [Sk1erLLC/Elementa#4]
**Describe the bug**
When you have a category with a bunch of options, performance is hit heavily wasting time trying to render but also being told to not render.

**To Reproduce**
Create a bunch of options using Vigilance, open the gui, watch everything come to a halt

**Screenshots**
A gui with ~30 options
![image](https://user-images.githubusercontent.com/36578995/77580877-193f4680-6eb3-11ea-94d1-ac143da08ea8.png)

A gui with ~200 options
![image](https://user-images.githubusercontent.com/36578995/77580915-278d6280-6eb3-11ea-9d19-4ec0012d1993.png)

**Comment by asbyth** [comment]
decided to profile to get more insight, seems like a major is also just because of minecraft's font renderer
![image](https://user-images.githubusercontent.com/36578995/77588436-40504500-6ec0-11ea-9682-404f02886c8d.png)

**Comment by FalseHonesty** [comment]
Yeah, the primary thing I believe to be the issue is not checking if something is outside the viewport before rendering.

**Comment by FalseHonesty** [comment]
Commits 5cada19c46a26a51b8cd99c4d223863da01067cf and 60095c6ecc24e9781b8e06b2787fdfa36d324749 should drastically improve this performance. There might still be some advancements to be made, but for now this should suffice. Please re-open this issue if you encounter more performance issues.
