### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/class_310

### ISSUE THREAD

**Issue by CommandCracker8** [Sk1erLLC/Elementa#44]
**Describe the bug**
When trying to create a GUI, the following happens: https://pastebin.com/LfqUyESW

**To Reproduce**
I'm not entirely sure what to write here

**Expected behavior**
The GUI to open

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Of what?

**Comment by Sychic** [comment]
Hey, looks like something's wrong with your build.gradle. Can you either send it here or in our [discord](https://discord.gg/essential)?

**Comment by CommandCracker8** [comment]
Heya,

My code seems to literally no longer exist on my computer, I haven no clue what happened. I'll recreate the project and see if the issue still occurs.

**Comment by CommandCracker8** [comment]
Alright I have the error again, here's my build.gradle:
https://www.toptal.com/developers/hastebin/naxehaquhu.gradle

**Comment by Sychic** [comment]
Ah yeah that's an issue with the readme that i'll have to fix, you want to be using `modImplementation` instead of `implementation` for elementa

**Comment by CommandCracker8** [comment]
Ah I did wonder XD Thanks

**Comment by Sychic** [comment]
Yep, you just call draw on the window to render during a hud render event. Not too sure on how it'd work in fabric
